[build]
command = "next build"
output = ".next"

[build.environment]
NODE_VERSION = "22.16.0"
NEXT_TELEMETRY_DISABLED = "1"

[site]
bucket = ".next"

# Cloudflare Pages configuration
pages_build_output_dir = ".next" 